server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: '1234'
    platform: mysql
    schema: classpath:/sql/schema.sql
    url: jdbc:mysql://localhost/delivery_order?verifyServerCertificate=false&useSSL=false&requireSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true

authserver:
  hostname: http://localhost:9092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
