server:
  port: 8071

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db-ms-partner
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

cache:
  partner:
    duration-in-minutes: 60

rabbitmq:
  exchange: partnerExchange
  queue: partnerQueueNew
  routingkey: partnerRoutingkey